import "./globals.css";
import Navigation from "@/components/Navigation";

export const metadata = {
	title: "EJ Law",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
